version: '3.8'

#name persistent volumes
volumes:
  mongo_data:
  redis_data:


services:

  app:
    image: todo-front-development
    build:
      context: ./todo-frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    ports:
      - 3000:3000
    container_name: todo-front-development

  mongo:
    image: mongo
    ports:
      - 27017:27017 #mongo default
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pw
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db #refer to persistent volume

  redis:
    image: redis
    ports:
      - 6379:6379 #redis default
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - ./todo-backend/redis_data:/data #refer to persistent volume

  server:
    image: todo-back-development
    ports:
      - 3001:3001
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    command: [ 'npm', 'run', 'dev' ] #overrides CMD in dev.Dockerfile
    container_name: todo-back-development
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
